server:
  port: 8888
spring:
  application:
    name: spring-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vconte01/micro_properties
          force-pull: true
          default-label: main
